/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.iudigital.carcenter;

import com.iudigital.carcenter.controller.CarController;
import com.iudigital.carcenter.domain.Car;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorge Jc
 */
public class Main2 extends javax.swing.JFrame {

    private final CarController carController;
    private final static String[] COLUMNS = {"ID", "MARCA", "MODELO", "AÑO",
        "COLOR", "TRANSMISION"};
    private final static String SELECCIONE = "--SELECCIONE--";

    /**
     * Creates new form Main2
     */
    public Main2() {
        initComponents(); // se inician los componentes de la vista, viene por defecto
        txtCarId.setEditable(false); // para que el campo ID en actualizar no sea pueda editar
        carController = new CarController(); // hacemos una instancia de CarController
        listCars(); //llamamos al metodo listCars
        addListener();

    }

    private void listCars() {

        cbxCars.removeAllItems(); //usamos este metodo para que no salga la opcion seleccione varias veces
        Car car1 = new Car(); // hacemos una instancia de Car para mostrar un carro ("--SELECCIONE--")
        car1.setMarca(SELECCIONE); // lo colocamos en marca por el metodo to string de Car 
        car1.setModelo(""); // concatenamos en el conbo box lo que queramos que nos muestre de carro
        cbxCars.addItem(car1); //agregamos el nuevo carro (--SELECCIONE--) al combo box
        tblCars.removeAll(); //limpiamos la tabla para que no se muestre la opciones repetidas

        DefaultTableModel defaultTableModel = new DefaultTableModel();
        for (String COLUMN : COLUMNS) {
            defaultTableModel.addColumn(COLUMN);
        }
        tblCars.setModel(defaultTableModel);

        try {
            List<Car> cars = carController.obtenerCarros();
            if (cars.isEmpty()) {
                return;
            }
            defaultTableModel.setRowCount(cars.size());
            int row = 0;
            for (Car car : cars) {
                defaultTableModel.setValueAt(car.getId(), row, 0);
                defaultTableModel.setValueAt(car.getMarca(), row, 1);
                defaultTableModel.setValueAt(car.getModelo(), row, 2);
                defaultTableModel.setValueAt(car.getAnho(), row, 3);
                defaultTableModel.setValueAt(car.getColor(), row, 4);
                defaultTableModel.setValueAt(car.getTransmission(), row, 5);
                row++;

                cbxCars.addItem(car);
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }

    private void addListener() {
        cbxCars.addItemListener(event -> {
            Car selectedCar = (Car) event.getItem();
            if (selectedCar.getMarca().equals(SELECCIONE)) {
                txtCarId.setText("");
                txtBrandEdit.setText("");
                txtModelEdit.setText("");
                txtAnhoEdit.setText("");
                txtColorEdit.setText("");
                txtTransmissionEdit.setText("");

            } else {
                txtCarId.setText(String.valueOf(selectedCar.getId()));
                txtBrandEdit.setText(selectedCar.getMarca());
                txtModelEdit.setText(selectedCar.getModelo());
                txtAnhoEdit.setText(selectedCar.getAnho());
                txtColorEdit.setText(selectedCar.getColor());
                txtTransmissionEdit.setText(selectedCar.getTransmission());

            }
            System.out.println("selectedCard = " + selectedCar);

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        lblTitle = new javax.swing.JLabel();
        jTPanels = new javax.swing.JTabbedPane();
        jPCar = new javax.swing.JPanel();
        jPCampos = new javax.swing.JPanel();
        lblBrand = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        lblModel = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        lblAnho = new javax.swing.JLabel();
        txtAnho = new javax.swing.JTextField();
        lblColor = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        lblTransmission = new javax.swing.JLabel();
        txtTransmission = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCars = new javax.swing.JTable();
        jPUser = new javax.swing.JPanel();
        jPEditar = new javax.swing.JPanel();
        cbxCars = new javax.swing.JComboBox<>();
        lblCarros = new javax.swing.JLabel();
        lblCarId = new javax.swing.JLabel();
        txtCarId = new javax.swing.JTextField();
        lblMarcaEdit = new javax.swing.JLabel();
        lblModelEdit = new javax.swing.JLabel();
        lblAnhoEdit = new javax.swing.JLabel();
        lblColorEdit = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBrandEdit = new javax.swing.JTextField();
        txtModelEdit = new javax.swing.JTextField();
        txtAnhoEdit = new javax.swing.JTextField();
        txtColorEdit = new javax.swing.JTextField();
        txtTransmissionEdit = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setText("Car Center");
        lblTitle.setName("lblTitle"); // NOI18N

        jPCampos.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite los Siguientes Campos"));

        lblBrand.setText("MARCA");

        lblModel.setText("MODELO");

        lblAnho.setText("AÑO");

        lblColor.setText("COLOR");

        lblTransmission.setText("TRANSMISION");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPCamposLayout = new javax.swing.GroupLayout(jPCampos);
        jPCampos.setLayout(jPCamposLayout);
        jPCamposLayout.setHorizontalGroup(
            jPCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCamposLayout.createSequentialGroup()
                .addGroup(jPCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCamposLayout.createSequentialGroup()
                        .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblModel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPCamposLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBrand)))
                .addGap(34, 34, 34)
                .addGroup(jPCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGuardar)
                    .addGroup(jPCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtAnho, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAnho)))
                .addGap(35, 35, 35)
                .addGroup(jPCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblColor)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTransmission, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTransmission))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPCamposLayout.setVerticalGroup(
            jPCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCamposLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrand)
                    .addComponent(lblModel)
                    .addComponent(lblAnho)
                    .addComponent(lblColor)
                    .addComponent(lblTransmission))
                .addGap(8, 8, 8)
                .addGroup(jPCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTransmission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(btnGuardar)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        tblCars.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tblCars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblCars);

        javax.swing.GroupLayout jPCarLayout = new javax.swing.GroupLayout(jPCar);
        jPCar.setLayout(jPCarLayout);
        jPCarLayout.setHorizontalGroup(
            jPCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        jPCarLayout.setVerticalGroup(
            jPCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTPanels.addTab("Crear Carro", jPCar);

        jPEditar.setBorder(javax.swing.BorderFactory.createTitledBorder("Modifique los siguientes Campos"));

        lblCarros.setText("Carros");

        lblCarId.setText("ID");

        txtCarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarIdActionPerformed(evt);
            }
        });

        lblMarcaEdit.setText("MARCA");

        lblModelEdit.setText("MODELO");

        lblAnhoEdit.setText("AÑO");

        lblColorEdit.setText("COLOR");

        jLabel6.setText("TRANSMISION");

        btnUpdate.setText("Actualizar");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Eliminar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPEditarLayout = new javax.swing.GroupLayout(jPEditar);
        jPEditar.setLayout(jPEditarLayout);
        jPEditarLayout.setHorizontalGroup(
            jPEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPEditarLayout.createSequentialGroup()
                        .addGroup(jPEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPEditarLayout.createSequentialGroup()
                                .addComponent(lblCarId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(236, 236, 236))
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCarros)
                    .addComponent(cbxCars, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPEditarLayout.createSequentialGroup()
                        .addComponent(txtCarId, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBrandEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMarcaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblModelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAnhoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAnhoEdit))
                        .addGap(18, 18, 18)
                        .addGroup(jPEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtColorEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblColorEdit))
                        .addGap(18, 18, 18)
                        .addGroup(jPEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtTransmissionEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPEditarLayout.setVerticalGroup(
            jPEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCarros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxCars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarId)
                    .addComponent(lblModelEdit)
                    .addComponent(lblAnhoEdit)
                    .addComponent(lblColorEdit)
                    .addComponent(jLabel6)
                    .addComponent(lblMarcaEdit))
                .addGroup(jPEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPEditarLayout.createSequentialGroup()
                        .addGroup(jPEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCarId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBrandEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtColorEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTransmissionEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAnhoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEditarLayout.createSequentialGroup()
                        .addGap(0, 36, Short.MAX_VALUE)
                        .addGroup(jPEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete)
                            .addComponent(btnUpdate))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPUserLayout = new javax.swing.GroupLayout(jPUser);
        jPUser.setLayout(jPUserLayout);
        jPUserLayout.setHorizontalGroup(
            jPUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPUserLayout.setVerticalGroup(
            jPUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        jTPanels.addTab("Editar Carro", jPUser);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jTPanels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addGap(4, 4, 4)
                .addComponent(jTPanels, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if (txtBrand.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite marca");
            txtBrand.requestFocus();
            return;
        }

        if (txtModel.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debe digitar Modelo");
            txtBrand.requestFocus();
            return;
        }

        if (txtAnho.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Año");
            txtBrand.requestFocus();
            return;
        }

        if (txtColor.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Color");
            txtBrand.requestFocus();
            return;
        }

        if (txtTransmission.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite tipo Transmisión");
            txtBrand.requestFocus();
            return;
        }

        Car car = new Car();
        car.setMarca(txtBrand.getText().trim());
        car.setModelo(txtModel.getText().trim());
        car.setAnho(txtAnho.getText().trim());
        car.setColor(txtColor.getText().trim());
        car.setTransmission(txtTransmission.getText().trim());

        try {
            carController.crear(car);
            txtBrand.setText("");
            txtModel.setText("");
            txtAnho.setText("");
            txtColor.setText("");
            txtTransmission.setText("");
            listCars();
            JOptionPane.showMessageDialog(null, "Carro creado con éxito");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Carro no pudo ser creado");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtCarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarIdActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        if (txtCarId.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccionar un carro de la Lista");
            txtCarId.requestFocus();
            return;
        }

        if (txtBrandEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite marca");
            txtBrandEdit.requestFocus();
            return;
        }

        if (txtModelEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debe digitar Modelo");
            txtModelEdit.requestFocus();
            return;
        }

        if (txtAnhoEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Año");
            txtAnhoEdit.requestFocus();
            return;
        }

        if (txtColorEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Color");
            txtColorEdit.requestFocus();
            return;
        }

        if (txtTransmissionEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite tipo Transmisión");
            txtTransmissionEdit.requestFocus();
            return;
        }

        Car car = new Car();
        car.setMarca(txtBrandEdit.getText().trim());
        car.setModelo(txtModelEdit.getText().trim());
        car.setAnho(txtAnhoEdit.getText().trim());
        car.setColor(txtColorEdit.getText().trim());
        car.setTransmission(txtTransmissionEdit.getText().trim());

        int opt = JOptionPane.showConfirmDialog(null, "Desea actualizar el carro", "Confirmar salida",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (opt == 0) {

            try {
                carController.actualizarCarro(Integer.parseInt(txtCarId.getText()), car);
                txtCarId.setText("");
                txtBrandEdit.setText("");
                txtModelEdit.setText("");
                txtAnhoEdit.setText("");
                txtColorEdit.setText("");
                txtTransmissionEdit.setText("");
                listCars();
                JOptionPane.showMessageDialog(null, "Se ha Actualizado el carro con éxito");
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "No fué posible crear el Carro");
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        if (txtCarId.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccionar un carro de la Lista");
            txtCarId.requestFocus();
            return;
        }

        int opt = JOptionPane.showConfirmDialog(null, "Está seguro de borrar carro", "Confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (opt == 0) {
            try {
                carController.eliminarCarro(Integer.parseInt(txtCarId.getText()));
                txtCarId.setText("");
                txtBrandEdit.setText("");
                txtModelEdit.setText("");
                txtAnhoEdit.setText("");
                txtColorEdit.setText("");
                txtTransmissionEdit.setText("");
                listCars();
                JOptionPane.showMessageDialog(null, "Se eliminó carro correctamente");
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "No se pudo Eliminar Carro");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<Car> cbxCars;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPCampos;
    private javax.swing.JPanel jPCar;
    private javax.swing.JPanel jPEditar;
    private javax.swing.JPanel jPUser;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTPanels;
    private javax.swing.JLabel lblAnho;
    private javax.swing.JLabel lblAnhoEdit;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblCarId;
    private javax.swing.JLabel lblCarros;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblColorEdit;
    private javax.swing.JLabel lblMarcaEdit;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblModelEdit;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTransmission;
    private javax.swing.JTable tblCars;
    private javax.swing.JTextField txtAnho;
    private javax.swing.JTextField txtAnhoEdit;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtBrandEdit;
    private javax.swing.JTextField txtCarId;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtColorEdit;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtModelEdit;
    private javax.swing.JTextField txtTransmission;
    private javax.swing.JTextField txtTransmissionEdit;
    // End of variables declaration//GEN-END:variables
}
